/** Declaration file generated by dts-gen */

declare module 'secure-ls' {

	export default class SecureLS {
		constructor(config: any)

		clear(): void

		get(key: string): any

		getAllKeys(): string[]

		remove(key: string): void

		removeAll(): void

		set(key: string, data: any): void

	}

}

